/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as FaleConoscoRouteImport } from './routes/fale-conosco'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as ProductFeedDotxmlRouteImport } from './routes/product-feed[.]xml'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as RastreioRouteImport } from './routes/rastreio'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as ColecaoSlugRouteImport } from './routes/colecao.$slug'
import { Route as PaginaSlugRouteImport } from './routes/pagina.$slug'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as ApiPublicPayoutbrWebhookRouteImport } from './routes/api/public/payoutbr-webhook'
import { Route as ApiPublicUploadImagesRouteImport } from './routes/api/public/upload-images'
import { Route as StorageV1SplatRouteImport } from './routes/storage.v1.$'
import { Route as StorageV1ObjectPublicSplatRouteImport } from './routes/storage.v1.object.public.$'
import { Route as StorageV1RenderImagePublicSplatRouteImport } from './routes/storage.v1.render.image.public.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const FaleConoscoRoute = FaleConoscoRouteImport.update({
  id: '/fale-conosco',
  path: '/fale-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductFeedDotxmlRoute = ProductFeedDotxmlRouteImport.update({
  id: '/product-feed.xml',
  path: '/product-feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreioRoute = RastreioRouteImport.update({
  id: '/rastreio',
  path: '/rastreio',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoSlugRoute = ColecaoSlugRouteImport.update({
  id: '/colecao/$slug',
  path: '/colecao/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginaSlugRoute = PaginaSlugRouteImport.update({
  id: '/pagina/$slug',
  path: '/pagina/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPayoutbrWebhookRoute =
  ApiPublicPayoutbrWebhookRouteImport.update({
    id: '/api/public/payoutbr-webhook',
    path: '/api/public/payoutbr-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUploadImagesRoute = ApiPublicUploadImagesRouteImport.update({
  id: '/api/public/upload-images',
  path: '/api/public/upload-images',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageV1SplatRoute = StorageV1SplatRouteImport.update({
  id: '/storage/v1/$',
  path: '/storage/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageV1ObjectPublicSplatRoute =
  StorageV1ObjectPublicSplatRouteImport.update({
    id: '/storage/v1/object/public/$',
    path: '/storage/v1/object/public/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const StorageV1RenderImagePublicSplatRoute =
  StorageV1RenderImagePublicSplatRouteImport.update({
    id: '/storage/v1/render/image/public/$',
    path: '/storage/v1/render/image/public/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/busca': typeof BuscaRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/product-feed.xml': typeof ProductFeedDotxmlRoute
  '/quem-somos': typeof QuemSomosRoute
  '/rastreio': typeof RastreioRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/pagina/$slug': typeof PaginaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/payoutbr-webhook': typeof ApiPublicPayoutbrWebhookRoute
  '/api/public/upload-images': typeof ApiPublicUploadImagesRoute
  '/storage/v1/$': typeof StorageV1SplatRoute
  '/storage/v1/object/public/$': typeof StorageV1ObjectPublicSplatRoute
  '/storage/v1/render/image/public/$': typeof StorageV1RenderImagePublicSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/busca': typeof BuscaRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/product-feed.xml': typeof ProductFeedDotxmlRoute
  '/quem-somos': typeof QuemSomosRoute
  '/rastreio': typeof RastreioRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/pagina/$slug': typeof PaginaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/payoutbr-webhook': typeof ApiPublicPayoutbrWebhookRoute
  '/api/public/upload-images': typeof ApiPublicUploadImagesRoute
  '/storage/v1/$': typeof StorageV1SplatRoute
  '/storage/v1/object/public/$': typeof StorageV1ObjectPublicSplatRoute
  '/storage/v1/render/image/public/$': typeof StorageV1RenderImagePublicSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/busca': typeof BuscaRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/product-feed.xml': typeof ProductFeedDotxmlRoute
  '/quem-somos': typeof QuemSomosRoute
  '/rastreio': typeof RastreioRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/pagina/$slug': typeof PaginaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/payoutbr-webhook': typeof ApiPublicPayoutbrWebhookRoute
  '/api/public/upload-images': typeof ApiPublicUploadImagesRoute
  '/storage/v1/$': typeof StorageV1SplatRoute
  '/storage/v1/object/public/$': typeof StorageV1ObjectPublicSplatRoute
  '/storage/v1/render/image/public/$': typeof StorageV1RenderImagePublicSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/busca'
    | '/cadastro'
    | '/carrinho'
    | '/checkout'
    | '/contato'
    | '/fale-conosco'
    | '/favoritos'
    | '/login'
    | '/minha-conta'
    | '/product-feed.xml'
    | '/quem-somos'
    | '/rastreio'
    | '/recuperar-senha'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/auth/confirm'
    | '/colecao/$slug'
    | '/pagina/$slug'
    | '/produto/$slug'
    | '/api/public/payoutbr-webhook'
    | '/api/public/upload-images'
    | '/storage/v1/$'
    | '/storage/v1/object/public/$'
    | '/storage/v1/render/image/public/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/busca'
    | '/cadastro'
    | '/carrinho'
    | '/checkout'
    | '/contato'
    | '/fale-conosco'
    | '/favoritos'
    | '/login'
    | '/minha-conta'
    | '/product-feed.xml'
    | '/quem-somos'
    | '/rastreio'
    | '/recuperar-senha'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/auth/confirm'
    | '/colecao/$slug'
    | '/pagina/$slug'
    | '/produto/$slug'
    | '/api/public/payoutbr-webhook'
    | '/api/public/upload-images'
    | '/storage/v1/$'
    | '/storage/v1/object/public/$'
    | '/storage/v1/render/image/public/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/busca'
    | '/cadastro'
    | '/carrinho'
    | '/checkout'
    | '/contato'
    | '/fale-conosco'
    | '/favoritos'
    | '/login'
    | '/minha-conta'
    | '/product-feed.xml'
    | '/quem-somos'
    | '/rastreio'
    | '/recuperar-senha'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/auth/confirm'
    | '/colecao/$slug'
    | '/pagina/$slug'
    | '/produto/$slug'
    | '/api/public/payoutbr-webhook'
    | '/api/public/upload-images'
    | '/storage/v1/$'
    | '/storage/v1/object/public/$'
    | '/storage/v1/render/image/public/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BuscaRoute: typeof BuscaRoute
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContatoRoute: typeof ContatoRoute
  FaleConoscoRoute: typeof FaleConoscoRoute
  FavoritosRoute: typeof FavoritosRoute
  LoginRoute: typeof LoginRoute
  MinhaContaRoute: typeof MinhaContaRoute
  ProductFeedDotxmlRoute: typeof ProductFeedDotxmlRoute
  QuemSomosRoute: typeof QuemSomosRoute
  RastreioRoute: typeof RastreioRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  ColecaoSlugRoute: typeof ColecaoSlugRoute
  PaginaSlugRoute: typeof PaginaSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiPublicPayoutbrWebhookRoute: typeof ApiPublicPayoutbrWebhookRoute
  ApiPublicUploadImagesRoute: typeof ApiPublicUploadImagesRoute
  StorageV1SplatRoute: typeof StorageV1SplatRoute
  StorageV1ObjectPublicSplatRoute: typeof StorageV1ObjectPublicSplatRoute
  StorageV1RenderImagePublicSplatRoute: typeof StorageV1RenderImagePublicSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fale-conosco': {
      id: '/fale-conosco'
      path: '/fale-conosco'
      fullPath: '/fale-conosco'
      preLoaderRoute: typeof FaleConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-feed.xml': {
      id: '/product-feed.xml'
      path: '/product-feed.xml'
      fullPath: '/product-feed.xml'
      preLoaderRoute: typeof ProductFeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreio': {
      id: '/rastreio'
      path: '/rastreio'
      fullPath: '/rastreio'
      preLoaderRoute: typeof RastreioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao/$slug': {
      id: '/colecao/$slug'
      path: '/colecao/$slug'
      fullPath: '/colecao/$slug'
      preLoaderRoute: typeof ColecaoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagina/$slug': {
      id: '/pagina/$slug'
      path: '/pagina/$slug'
      fullPath: '/pagina/$slug'
      preLoaderRoute: typeof PaginaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payoutbr-webhook': {
      id: '/api/public/payoutbr-webhook'
      path: '/api/public/payoutbr-webhook'
      fullPath: '/api/public/payoutbr-webhook'
      preLoaderRoute: typeof ApiPublicPayoutbrWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload-images': {
      id: '/api/public/upload-images'
      path: '/api/public/upload-images'
      fullPath: '/api/public/upload-images'
      preLoaderRoute: typeof ApiPublicUploadImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage/v1/$': {
      id: '/storage/v1/$'
      path: '/storage/v1/$'
      fullPath: '/storage/v1/$'
      preLoaderRoute: typeof StorageV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage/v1/object/public/$': {
      id: '/storage/v1/object/public/$'
      path: '/storage/v1/object/public/$'
      fullPath: '/storage/v1/object/public/$'
      preLoaderRoute: typeof StorageV1ObjectPublicSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage/v1/render/image/public/$': {
      id: '/storage/v1/render/image/public/$'
      path: '/storage/v1/render/image/public/$'
      fullPath: '/storage/v1/render/image/public/$'
      preLoaderRoute: typeof StorageV1RenderImagePublicSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BuscaRoute: BuscaRoute,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  ContatoRoute: ContatoRoute,
  FaleConoscoRoute: FaleConoscoRoute,
  FavoritosRoute: FavoritosRoute,
  LoginRoute: LoginRoute,
  MinhaContaRoute: MinhaContaRoute,
  ProductFeedDotxmlRoute: ProductFeedDotxmlRoute,
  QuemSomosRoute: QuemSomosRoute,
  RastreioRoute: RastreioRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  ColecaoSlugRoute: ColecaoSlugRoute,
  PaginaSlugRoute: PaginaSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiPublicPayoutbrWebhookRoute: ApiPublicPayoutbrWebhookRoute,
  ApiPublicUploadImagesRoute: ApiPublicUploadImagesRoute,
  StorageV1SplatRoute: StorageV1SplatRoute,
  StorageV1ObjectPublicSplatRoute: StorageV1ObjectPublicSplatRoute,
  StorageV1RenderImagePublicSplatRoute: StorageV1RenderImagePublicSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
